on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

name: test-coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
      MYSQL_HOST: "localhost"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    steps:
      - uses: actions/checkout@v5
      
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true     

      - name: Set up MySQL, ubuntu only
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;' -uroot -proot

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")
        shell: Rscript {0}
